export const countryCodeList = [
  { country: "Austria", code: "+43", flag: "🇦🇹" },
  { country: "Albania", code: "+355", flag: "🇦🇱" },
  { country: "Belarus", code: "+375", flag: "🇧🇾" },
  { country: "Belgium", code: "+32", flag: "🇧🇪" },
  { country: "Bulgaria", code: "+359", flag: "🇧🇬" },
  { country: "United Kingdom", code: "+44", flag: "🇬🇧" },
  { country: "Hungary", code: "+36", flag: "🇭🇺" },
  { country: "Germany", code: "+49", flag: "🇩🇪" },
  { country: "Greece", code: "+30", flag: "🇬🇷" },
  { country: "Denmark", code: "+45", flag: "🇩🇰" },
  { country: "Ireland", code: "+353", flag: "🇮🇪" },
  { country: "Iceland", code: "+354", flag: "🇮🇸" },
  { country: "Spain", code: "+34", flag: "🇪🇸" },
  { country: "Italy", code: "+39", flag: "🇮🇹" },
  { country: "Kazakhstan", code: "+7", flag: "🇰🇿" },
  { country: "Latvia", code: "+371", flag: "🇱🇻" },
  { country: "Lithuania", code: "+370", flag: "🇱🇹" },
  { country: "Luxembourg", code: "+352", flag: "🇱🇺" },
  { country: "North Macedonia", code: "+389", flag: "🇲🇰" },
  { country: "Moldova", code: "+373", flag: "🇲🇩" },
  { country: "Netherlands", code: "+31", flag: "🇳🇱" },
  { country: "Norway", code: "+47", flag: "🇳🇴" },
  { country: "Poland", code: "+48", flag: "🇵🇱" },
  { country: "Portugal", code: "+351", flag: "🇵🇹" },
  { country: "Romania", code: "+40", flag: "🇷🇴" },
  { country: "Serbia", code: "+381", flag: "🇷🇸" },
  { country: "Slovakia", code: "+421", flag: "🇸🇰" },
  { country: "Slovenia", code: "+386", flag: "🇸🇮" },
  { country: "Turkey", code: "+90", flag: "🇹🇷" },
  { country: "Ukraine", code: "+380", flag: "🇺🇦" },
  { country: "Finland", code: "+358", flag: "🇫🇮" },
  { country: "France", code: "+33", flag: "🇫🇷" },
  { country: "Croatia", code: "+385", flag: "🇭🇷" },
  { country: "Montenegro", code: "+382", flag: "🇲🇪" },
  { country: "Czech Republic", code: "+420", flag: "🇨🇿" },
  { country: "Switzerland", code: "+41", flag: "🇨🇭" },
  { country: "Sweden", code: "+46", flag: "🇸🇪" },
  { country: "Estonia", code: "+372", flag: "🇪🇪" },
  { country: "Jamaica", code: "+1", flag: "🇯🇲" },
  { country: "Japan", code: "+81", flag: "🇯🇵" },
];
